[package]
name = "load-balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
axum-macros = "0.5.0"
eyre = "0.6.12"
hyper = "1.4.1"
log = "0.4.22"
reqwest = "0.12.8"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
